INDICATORS = [
    'volume',
    'VIXY',
    'day_of_week', 
    # 'is_holiday', 
    # 'returns', 
    # 'moving_Avg',
    # 'price_Change', 
    # 'volume_Change', 
    # 'Rolling_Mean', 
    # 'Rolling_Std', 
    'RSI',
    'EMA', 
    'MACD', 
    'SMA_5', 
    'SMA_10', 
    'SMA_20', 
    'SMA_50', 
    'BBANDS_Upper',
    'BBANDS_Middle', 
    'BBANDS_Lower', 
    'VWAP', 
    'ROC', 
    'ATR', 
    'CCI',
    'WilliamsR', 
    'Stochastic_SlowK', 
    'Stochastic_SlowD', 
    'MFI',
    # 'fnn_pred'
]
